pmtiles:
  sources:
    airports: ${OUTPUT_ROOT}/pmtiles/airports.pmtiles
    base: ${OUTPUT_ROOT}/pmtiles/base.pmtiles
    world: ${OUTPUT_ROOT}/pmtiles/world.pmtiles
    africa: ${OUTPUT_ROOT}/pmtiles/regions/africa.pmtiles
    antarctica: ${OUTPUT_ROOT}/pmtiles/regions/antarctica.pmtiles
    asia: ${OUTPUT_ROOT}/pmtiles/regions/asia.pmtiles
    australia-oceania: ${OUTPUT_ROOT}/pmtiles/regions/australia-oceania.pmtiles
    europe: ${OUTPUT_ROOT}/pmtiles/regions/europe.pmtiles
    north-america: ${OUTPUT_ROOT}/pmtiles/regions/north-america.pmtiles
    south-america: ${OUTPUT_ROOT}/pmtiles/regions/south-america.pmtiles
    ontario: ${OUTPUT_ROOT}/pmtiles/regions/north-america/canada/ontario.pmtiles
    us-northeast: ${OUTPUT_ROOT}/pmtiles/regions/north-america/us-northeast.pmtiles
    us-south: ${OUTPUT_ROOT}/pmtiles/regions/north-america/us-south.pmtiles
    us: ${OUTPUT_ROOT}/pmtiles/regions/north-america/us.pmtiles
    connecticut: ${OUTPUT_ROOT}/pmtiles/regions/north-america/us/connecticut.pmtiles
    delaware: ${OUTPUT_ROOT}/pmtiles/regions/north-america/us/delaware.pmtiles
    district-of-columbia: ${OUTPUT_ROOT}/pmtiles/regions/north-america/us/district-of-columbia.pmtiles
    florida: ${OUTPUT_ROOT}/pmtiles/regions/north-america/us/florida.pmtiles
    maine: ${OUTPUT_ROOT}/pmtiles/regions/north-america/us/maine.pmtiles
    maryland: ${OUTPUT_ROOT}/pmtiles/regions/north-america/us/maryland.pmtiles
    massachusetts: ${OUTPUT_ROOT}/pmtiles/regions/north-america/us/massachusetts.pmtiles
    new-york: ${OUTPUT_ROOT}/pmtiles/regions/north-america/us/new-york.pmtiles
    pennsylvania: ${OUTPUT_ROOT}/pmtiles/regions/north-america/us/pennsylvania.pmtiles

sprites:
  sources:
    mapbox: ${OUTPUT_ROOT}/sprite/mapbox
    fltsci: ${OUTPUT_ROOT}/sprite/fltsci

fonts:
  - ${OUTPUT_ROOT}/fonts/ttf
