FROM ghcr.io/maplibre/martin:latest

WORKDIR /app

ENV OUTPUT_ROOT=/app/output

COPY ./config.yaml /app/config.yaml
COPY ./output/sprite /app/output/sprite
COPY ./output/pmtiles /app/output/pmtiles
COPY ./output/sprite /app/output/sprite
COPY ./output/fonts /app/output/fonts

CMD ["--config", "/app/config.yaml"]
