services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./cache:/var/cache/nginx
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/ssl/certs
    depends_on:
      - martin

  martin:
    image: ghcr.io/maplibre/martin
    restart: unless-stopped
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./output:/app/output
    command: ["--config", "/app/config.yaml"]
    environment:
      - OUTPUT_ROOT=/app/output
